### ISSUE TITLE
Linux compile problem

### ISSUE THREAD

**Issue by toorisrael** [yourmnbbn/tiny-csgo-client#4]
Hi. I'm getting this error when trying to compile for linux:
```
[ 16%] Building CXX object CMakeFiles/tiny-csgo-client.dir/cl-main.cpp.o
In file included from /home/x/Desktop/tiny-csgo-client-main/cl-main.cpp:1:
In file included from /home/x/Desktop/tiny-csgo-client-main/include/client.hpp:16:
In file included from /home/x/Desktop/tiny-csgo-client-main/include/common/bitbuf.h:19:
In file included from /home/x/Desktop/tiny-csgo-client-main/include/hl2sdk-csgo/public/mathlib/mathlib.h:11:
In file included from /home/x/Desktop/tiny-csgo-client-main/include/hl2sdk-csgo/public/tier0/basetypes.h:34:
In file included from /home/x/Desktop/tiny-csgo-client-main/include/hl2sdk-csgo/public/tier0/platform.h:33:
/home/x/Desktop/tiny-csgo-client-main/include/hl2sdk-csgo/public/tier0/wchartypes.h:76:10: fatal error: 'tchar.h' file not found
```
I've tried to figure it out by myself, sadly without success.

**Comment by yourmnbbn** [comment]
This is because missing pre-defined macro `POSIX`. Maybe you are using clang? So far on linux I've only configured cmake for gcc and tested with gcc 10.3.0. Other compilers are not configured and tested yet. 

If you want to play with clang you can try to apply gcc configs for all the other compilers in linux by changing this:
https://github.com/yourmnbbn/tiny-csgo-client/blob/209058eb893a718f87a1a0f024693140f11e94f6/CMakeLists.txt#L49
into
```cmake
elseif(UNIX)
```

**Comment by toorisrael** [comment]
This could be closed, as I've fixed it using gcc instead of clang. Sorry for the delay with response.
