### ISSUE TITLE
Questions about ticket

### ISSUE THREAD

**Issue by saguaro-yerba** [yourmnbbn/tiny-csgo-client#5]
Hello, very good job with this client, a pice of good software. I am full of admiration for the work done!
I have some questions about tickets, I am using limited version of client on Linux:
1. How long is the validity of the ticket after generating? How much time do I have to use it for connection after generating?
2. After generating the ticket, steam can be turned off?

Sometimes the client joins the server correctly, but is disconnected after equally 90 seconds. I don't know what I'm doing wrong. I compiled the client with gcc10 and run it on the Alpine Docker image (same problem on Ubuntu).

I will be grateful for help.
Best regards and have a good day!

**Comment by yourmnbbn** [comment]
Hi, limited version currently can't maintain an alive connection unless [this](https://github.com/perilouswithadollarsign/cstrike15_src/blob/f82112a2388b841d72cb62ca48ab1846dfcc11c8/engine/sv_steamauth.cpp#L703) is bypassed or you keep ticketgen program running to keep the connection between client and steam master server. 

1. Ticket is valid for days long, I can't tell the exact number so far but approximately 6 or 7 days long or changed weekly I guess.
2. Yes, but it could lead to steam validation failed unless you bypass the validation callback as mentioned above.

Limited version separates the steam and the client for a better management of the multi-clients. If you want to try to fake the players count, It's recommended to keep ticketgens running elsewhere(with each steam account login) and tiny-clients running in a single environment.

EDIT: Sometimes the ticket will be invalid immediately after generating, the behavior of the ticket is not fully figured out for now.

**Comment by toorisrael** [comment]
Few months ago I've tested bypassing OnValidateAuthTicketResponseHelper and some other functions so you will not get dropped from server with terminated Steam. Although it will let you stay on server, you will still be deauthenticated, which means 0 players in Steam api / internet browser.

**Comment by yourmnbbn** [comment]
> Few months ago I've tested bypassing OnValidateAuthTicketResponseHelper and some other functions so you will not get dropped from server with terminated Steam. Although it will let you stay on server, you will still be deauthenticated, which means 0 players in Steam api / internet browser.

Yep, that's why I recommended keeping ticketgen running elsewhere(sandbox, vm or something else). It will keep telling steam that the owner of that account is playing csgo. So running multiple clients without steam in other environments while being fully authenticated is possible. 

But since the behavior of the ticket is not as expected, I'll keep working on it when I have time.

**Comment by toorisrael** [comment]
I've not yet tested this exact solution, but I've already tested generating tickets before tiny-csgo-client existed with node.js, and as far as I remember generating new ticket for the already authenticated account will immediately deauthenticate connected client.
Also main problem for me is running many Steam instances, as Steam is wasting so much CPU time.

**Comment by HexMr** [comment]
@yourmnbbn Hello, you have done a very good job. I have a little suggestion related to this program. I see that despite the "weight loss" of the client itself, steam is needed for the program to work. Rather, most people expected to be able to close steam in this client version. The main problem is the very high consumption of steam resources because running a large number of clients requires a lot of resources. What do you think about adjusting this client version to steamCMD? I don't know if it is entirely feasible as steamCMD is limited. I am waiting for your answer.

**Comment by toorisrael** [comment]
Sadly CSGO (game client) doesn't work with SteamCMD, but I've only tested this on windows.

**Comment by saguaro-yerba** [comment]
Ok, I understand, thanks everyone for the explanation.
